#pragma once

#include "Boolean.h"
#include "Char.h"
#include "SByte.h"
#include "Byte.h"
#include "Int16.h"
#include "UInt16.h"
#include "Int32.h"
#include "UInt32.h"
#include "Int64.h"
#include "UInt64.h"
#include "Single.h"
#include "Double.h"
#include "Decimal.h"
#include "DateTime.h"
#include "Object.h"